FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 libglib2.0-0 libgomp1 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY services/ocr/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/ocr/src ./src
COPY shared ./shared

CMD ["python", "-m", "src.main"]
