"""add video_jobs table and plate_records youtube fields

Revision ID: ee06fa0400f2
Revises: a80e1c1bd254
Create Date: 2026-03-30 05:49:38.495361
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee06fa0400f2'
down_revision: Union[str, None] = 'a80e1c1bd254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add 'youtube' to the existing record_source_enum
    op.execute("ALTER TYPE record_source_enum ADD VALUE IF NOT EXISTS 'youtube'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloading', 'processing', 'completed', 'failed', name='video_job_status_enum'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('processed_frames', sa.Integer(), nullable=False),
    sa.Column('plates_found', sa.Integer(), nullable=False),
    sa.Column('frame_interval_sec', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_job_status', 'video_jobs', ['status'], unique=False)
    op.add_column('plate_records', sa.Column('video_job_id', sa.UUID(), nullable=True))
    op.add_column('plate_records', sa.Column('frame_timestamp', sa.Float(), nullable=True))
    op.create_index('idx_plate_video_job', 'plate_records', ['video_job_id'], unique=False)
    op.create_foreign_key(None, 'plate_records', 'video_jobs', ['video_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plate_records', type_='foreignkey')
    op.drop_index('idx_plate_video_job', table_name='plate_records')
    op.drop_column('plate_records', 'frame_timestamp')
    op.drop_column('plate_records', 'video_job_id')
    op.drop_index('idx_video_job_status', table_name='video_jobs')
    op.drop_table('video_jobs')
    # ### end Alembic commands ###
